version: '3'
services:
  server:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "7001:7001"
    depends_on:
      - mongodb
    working_dir: /app
  mongodb:
    image: mongo:6.0.4
    ports:
      - 27018:27017
    volumes:
      - mongodata:/data/db-2
volumes:
  mongodata:
